# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a53d2c58682e8db55e651ee37949cf42f1b2af6ecb4435b68f14d0b6e93d2d2dabc0322f3f11c9732f03ea1b3a335fb819e4935b1cb9336af59a5321415b4d86

test:
  secret_key_base: 7b94d640468aa7e66085051095c593bc40e189d26c42bb5c1c057f6b7b7648470df61e0624fc56f01f4eb629f2f22218096fa145f16fb244a76db5d16e58935f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
